tasker/tasker/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from users import views
from django.urls import reverse_lazy
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('engineers/', include('engineers.urls', namespace='engineers')),
    path('technicians/', include('technicians.urls', namespace='technicians.urls')),

    #################### Регистрация, и смена пароля##########################
    path('login', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('signup/', views.SignUp.as_view(template_name='users/signup.html'),
         name='signup'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        success_url=reverse_lazy('password_reset_done')
    ), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('password_reset_complete')
    ), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change_form.html'),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),
    ##########################################################

    path('', include('users.urls', namespace='users')),

]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

tasker/users/urls.py
from django.urls import path


from . import views

app_name = 'users'

urlpatterns = [
    path('account_not_confirmed/', views.account_not_confirmed,
         name='account_not_confirmed'),
    path('', views.division_users,
         name='index'),
]

tasker/users/models.py
from django.db import models

tasker/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from branches.models import Branch
from engineers.models import Engineer
from technicians.models import Technician

User = get_user_model()


ROLE_CHOICES = (
    ('engineer', 'Инженер'),
    ('technician', 'Техник'),
)


class CreationForm(UserCreationForm):
    last_name = forms.CharField(required=True,
                                max_length=30,
                                label='Фамилия',
                                help_text='Введите фамилию',)
    first_name = forms.CharField(required=True,
                                 max_length=30,
                                 label='Имя',
                                 help_text='Введите имя')
    middle_name = forms.CharField(required=True,
                                  max_length=30,
                                  label='Отчество',
                                  help_text='Введите отчество',)
    phone_number = forms.CharField(required=False,
                                   max_length=20,
                                   label='Телефон',
                                   help_text='Введите телефон',)
    role = forms.ChoiceField(choices=ROLE_CHOICES,
                             label='Должность')
#    branch = forms.ChoiceField(
#        choices=[(branch.pk, branch.city) for branch in Branch.objects.all()],
#        label='Филиал')
#
#    class Meta(UserCreationForm.Meta):
#        model = User
#        fields = ('last_name', 'first_name', 'middle_name', 'phone_number',
#                  'username', 'email', 'role', 'branch')
#
#    def __init__(self, *args, **kwargs):
#        super().__init__(*args, **kwargs)
#        self.fields['branch'].choices = [
#            (branch.pk, branch.city) for branch in Branch.objects.all()]
#        self.fields['username'].label = 'Логин'
#
#    def clean_role(self):
#        role = self.cleaned_data.get('role')
#        if role not in dict(ROLE_CHOICES).keys():
#            raise forms.ValidationError('Недопустимая роль')
#        return role
#
#    def save(self, commit=True):
#        user = super().save(commit=False)
#        branch_id = self.cleaned_data['branch']
#        role = self.cleaned_data['role']
#        last_name = self.cleaned_data['last_name']
#        first_name = self.cleaned_data['first_name']
#        middle_name = self.cleaned_data['middle_name']
#        phone_number = self.cleaned_data['phone_number']
#        if commit:
#            user.save()
#            if role == 'technician':
#                tech = Technician.objects.create(
#                    user=user,
#                    branch_id=branch_id,
#                    last_name=last_name,
#                    first_name=first_name,
#                    middle_name=middle_name,
#                    phone=phone_number,
#                )
#            elif role == 'engineer':
#                eng = Engineer.objects.create(
#                    user=user,
#                    branch_id=branch_id,
#                    last_name=last_name,
#                    first_name=first_name,
#                    middle_name=middle_name,
#                    phone=phone_number,
#                )
#        return user

tasker/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import CreationForm
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from technicians.models import Technician
from engineers.models import Engineer
from django.shortcuts import render, redirect


@login_required
def division_users(request):
    user = request.user
    if Engineer.objects.filter(user=user).exists():
        success_url = reverse_lazy('engineers:index')
    elif Technician.objects.filter(user=user).exists():
        success_url = reverse_lazy('technicians:index')
    else:
        success_url = reverse_lazy('users:account_not_confirmed')
    return redirect(success_url)


def account_not_confirmed(request):
    return render(request, 'users/account_not_confirmed.html')


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('users:index')
    template_name = 'users/signup.html'

tasker/templates/users/account_not_confirmed.html
{% extends "users/login_base.html" %}
{% block title %}<title>Зарегистрироваться</title>{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="card">
      <div class="card-body">
        <p>Ваша учетная запись еще не подтверждена</p>
        <a href="{% url 'logout' %}" class="btn btn-link">
          Выйти
        </a>
        <a href="{% url 'login' %}" class="btn btn-link">
          Обновить
        </a>
      </div> 
    </div> 
</div> 
{% endblock %} 

tasker/templates/users/logged_out.html
{% extends 'users/login_base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}

    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
        <a href={% url 'login' %}> На главную </a>
      </div> <!-- card body -->
    </div> <!-- card -->

{% endblock %} 

tasker/templates/users/login.html
{% extends 'users/login_base.html' %}
{% block content %}
{% load user_filters %}
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          <div class="col">
            <a href="{% url 'signup' %}" class="btn btn-link">
              Регистрация
            </a>

          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->

{% endblock  %}

tasker/templates/users/login_base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    {% load user_filters %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/sign-in.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">
    
<main class="form-signin w-100 m-auto">
 {% block content %}тут что то должно быть{% endblock content %}
</main>


    
  </body>
</html>

tasker/templates/users/password_change_done.html
{% extends "users/login_base.html" %}
{% block title %}<title>Пароль изменён</title>{% endblock %}
{% block content %}    

            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div> <!-- card body -->
            </div> <!-- card -->

{% endblock %}

tasker/templates/users/password_change_form.html
{% extends "users/login_base.html" %}
{% block title %}<title>Изменение пароля</title>{% endblock %}
{% block content %}

            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                {% load user_filters %} {# Загружаем фильтры #}
                {% if form.errors %}
                    {% for field in form %} 
                      {% for error in field.errors %}            
                        <div class="alert alert-danger">
                          {{ error|escape }}
                        </div>
                      {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                {% endif %}
                <form method="post">
                  {% csrf_token %}
                  {% for field in form %}
                    <div class="form-group row my-3 p-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                    </label>    
                    {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                    </div>
                  {% endfor%}
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->

{% endblock %}

tasker/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}<title>Зарегистрироваться</title>{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Восстановление пароля завершено
      </div>
      <div class="card-body">
        <p>Ваш пароль был сохранен. Используйте его для входа</p>
        <a href="{% url 'users:login' %}">войти</a>
      </div> 
    </div> 
  </div>
</div> 
{% endblock %} 

tasker/templates/users/password_reset_confirm.html
{% extends "users/login_base.html" %}
{% block title %}<title>Новый пароль</title>{% endblock %}
{% block content %}	
{% load user_filters %}

{% if validlink %}   
            <div class="card">
              <div class="card-header">
                Введите новый пароль
              </div>
              <div class="card-body">
                {% if form.errors %}
                    {% for field in form %} 
                      {% for error in field.errors %}            
                        <div class="alert alert-danger">
                          {{ error|escape }}
                        </div>
                      {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endif %}
                <form method="post">
                  {% csrf_token %}
                  {% for field in form %}
                  <div class="form-group row my-3 p-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}             
                    </label>
                    {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                       <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                        >
                        {{ field.help_text|safe }}
                        </small>
                    {% endif %}     
                  </div>
                  {% endfor%}
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Назначить новый пароль
                    </button>
                  </div>
                  {% else %}                  
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->

        <!-- если использована неправильная ссылка -->
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Ошибка
              </div>
              <div class="card-body">
                <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        {% endif%}
{% endblock%}

tasker/templates/users/password_reset_done.html
{% extends "users/login_base.html" %}
{% block title %}<title>Сброс пароля прошёл успешно</title>{% endblock %}
{% block content %}

            <div class="card">
              <div class="card-header">
                Отправлено письмо
              </div>
              <div class="card-body">
                <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
              </div> 
            </div> 

{% endblock %}

tasker/templates/users/password_reset_form.html
{% extends "users/login_base.html" %}
{% block title %}<title>Сброс пароля</title>{% endblock %}
{% block content %}
            <div class="card">
              <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
              </div>
              <div class="card-body">
                {% load user_filters %}

                  <form method="post">
                    {% csrf_token %}
                    
                    {% for field in form %} 
                      <div class="form-group row my-3 p-3">
                        <label for="{{ field.id_for_label }}">
                          {{ field.label }}
                          {% if field.field.required %}
                            <span class="required text-danger">*</span>
                          {% endif %}
                        </label>    
                        {{ field|addclass:'form-control'}}
                        {% if field.help_text %}
                          <small 
                            id="{{ field.id_for_label }}-help"
                            class="form-text text-muted">
                            {{ field.help_text|safe }}
                          </small>
                        {% endif %}
                      </div>
                    {% endfor%}
                    <div class="col-md-6 offset-md-4">
                      <button type="submit" class="btn btn-primary">
                        Сбросить пароль
                      </button>
                    </div>
                  </form>
              </div>
            </div>
{% endblock %}

tasker/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    {% if form.errors %}
        <div class="alert alert-danger">
            {% for field in form %}
                {% for error in field.errors %}
                    <strong>{{ field.label }}:</strong> {{ error }}<br>
                {% endfor %}
            {% endfor %}
        </div>
    {% endif %}

    <button type="submit">Submit</button>
</form>
{% endblock %}

tasker/templates/users/signup.html
{% extends "users/login_base.html" %}
{% block title %}<title>Зарегистрироваться</title>{% endblock %}
{% block content %}

      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
            {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              <form method="post" action="{% url 'signup' %}">
                {% csrf_token %}
                {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                  </button>
                </div>
              </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->

{% endblock %} 