tasker/engineers/urls.py
from django.urls import path


from . import views

app_name = 'engineers'

urlpatterns = [
    path('', views.index,
         name='index'),
    path('service_zones/', views.service_zones, name='service_zones'),
    path('create_service_zone/', views.create_service_zone,
         name='create_service_zone'),
    path('service_zone/<int:service_zone_id>/delete/',
         views.service_zone_delete, name='service_zone_delete'),
    path('service_zone/<int:service_zone_id>/edit/',
         views.service_zone_edit, name='service_zone_edit'),
     path('service_zone/<int:service_zone_id>/deteil/',
         views.service_zone_deteil, name='service_zone_deteil'),
    path('technicians/', views.technicians, name='technicians'),
    path('technician/<int:technician_id>/detail/',
         views.technician_detail, name='technician_detail'),
    path('technician/<int:technician_id>/activate/',
         views.technician_activate, name='technician_activate'),
    path('technician/<int:technician_id>/deactivate/',
         views.technician_deactivate, name='technician_deactivate'),
    path('technician_zone/<int:technician_zone_id>/delete/',
         views.technician_zone_delete, name='technician_zone_delete'),
    path('fire_alarm_objects/', views.fire_alarm_objects,
         name='fire_alarm_objects'),
    path('fire_alarm_objects/<int:to_date>/', views.fire_alarm_objects_filter,
         name='fire_alarm_objects_filter'),
    path('fire_alarm_object/create/', views.create_fire_alarm_object,
         name='create_fire_alarm_object'),
    path('fire_alarm_object/<int:object_id>/edite/',
         views.fire_alarm_object_edite, name='fire_alarm_object_edite'),
    path('fire_alarm_object/<int:object_id>/delete/',
         views.fire_alarm_object_delete, name='fire_alarm_object_delete'),
    path('fire_alarm_object/<int:object_id>/detail/', views.fire_alarm_object_detail, name = 'fire_alarm_object_detail'),
    path('import_csv/', views.import_csv, name ='import_csv')
]

tasker/tasker/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from users import views
from django.urls import reverse_lazy
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('engineers/', include('engineers.urls', namespace='engineers')),
    path('technicians/', include('technicians.urls', namespace='technicians.urls')),

    #################### Регистрация, и смена пароля##########################
    path('login', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('signup/', views.SignUp.as_view(template_name='users/signup.html'),
         name='signup'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        success_url=reverse_lazy('password_reset_done')
    ), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('password_reset_complete')
    ), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change_form.html'),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),
    ##########################################################

    path('', include('users.urls', namespace='users')),

]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

tasker/technicians/urls.py
from django.urls import path


from . import views

app_name = 'technicians'

urlpatterns = [
    path('', views.index,
         name='index'),
    path('tasks/<int:to_date>/show/',
         views.tasks, name='tasks'),
    path('fire_alarm_objects/<int:to_date>/show/',
         views.fire_alarm_objects, name='fire_alarm_objects'),
    path('fire_alarm_object_service/<int:object_id>/create/',
         views.fire_alarm_object_service_create, name='fire_alarm_object_service_create'),
    path('fire_alarm_object_service/<int:object_id>/detail', views.fire_alarm_object_service_detail , name='fire_alarm_object_service_detail'),
    path('failed_service/<int:object_id>/create',views.failed_service_create, name= 'failed_service_create')
]

tasker/users/urls.py
from django.urls import path


from . import views

app_name = 'users'

urlpatterns = [
    path('account_not_confirmed/', views.account_not_confirmed,
         name='account_not_confirmed'),
    path('', views.division_users,
         name='index'),
]

tasker/engineers/models.py
from django.db import models
from django.contrib.auth import get_user_model
from branches.models import Branch
User = get_user_model()


class Engineer(models.Model):
    """
    Модель для хранения информации об инженерах.
    """
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name='пользователь',
        help_text='Пользователь, к которому относится инженер',
    )
    branch = models.ForeignKey(
        Branch,
        on_delete=models.CASCADE,
        verbose_name='филиал',
        help_text='Выберите филиал, к которому относится инженер'
    )
    is_active = models.BooleanField(
        default=False,
        verbose_name='активен',
        help_text='Укажите, активена ли учетная запись инженер',
    )
    last_name = models.CharField(
        max_length=30,
        verbose_name='фамилия',
        help_text='Фамилия инженера',
    )
    first_name = models.CharField(
        max_length=30,
        verbose_name='имя',
        help_text='Имя инженера',
    )
    middle_name = models.CharField(
        max_length=30,
        verbose_name='отчество',
        help_text='Отчество инженера',
    )
    phone = models.CharField(
        max_length=20,
        verbose_name='телефон',
        help_text='Телефон инженера',
    )
    photo = models.ImageField(
        upload_to='engineer_photos',
        blank=True,
        null=True,
        verbose_name='фото',
        help_text='Фото инженера',
    )

    class Meta:
        verbose_name = 'инженер'
        verbose_name_plural = 'инженеры'

    def __str__(self):
        return f"{self.last_name} {self.first_name} {self.middle_name}"

tasker/fire_alarm_objects/models.py
from django.db import models
import os
from django.core.files import File
from service_zones.models import ServiceZone
from branches.models import Branch
from django.utils import timezone
from dateutil.relativedelta import relativedelta
from service_оrganizations.models import ServiceOrganizations
from shapely.geometry import Polygon, Point
from technicians.models import Technician
from tasker.settings import MEDIA_ROOT


class Address(models.Model):
    """
    Модель адреса объекта
    """
    address = models.CharField(max_length=200, verbose_name="Адрес")
    latitude = models.FloatField(verbose_name="Широта", null=True, blank=True)
    longitude = models.FloatField(
        verbose_name="Долгота", null=True, blank=True)

    class Meta:
        verbose_name = 'Адрес'
        verbose_name_plural = 'Адреса'

    def __str__(self):
        return self.address

    def get_geopoint(self):
        return f'[{self.latitude},{self.longitude}]'
    
    def get_geopoint_v2(self):
        return f'{self.latitude},{self.longitude}'
    
    def get_navigator_link(self):
        return f'yandexnavi://build_route_on_map?lat_to={self.latitude}&lon_to={self.longitude}'


class FireAlarmObject(models.Model):
    FREQUENCY_CHOICES = (
        ('Ежемесячно', 'Ежемесячно'),
        ('Ежеквартально', 'Ежеквартально'),
    )

    name = models.CharField(
        max_length=500,
        verbose_name='название объекта',
        help_text='Название объекта, на котором установлена пожарная сигнализация.'
    )

    frequency = models.CharField(
        max_length=15,
        choices=FREQUENCY_CHOICES,
        verbose_name='периодичность обслуживания',
        help_text='Периодичность обслуживания пожарной сигнализации на объекте.'
    )

    last_service_date = models.DateField(
        verbose_name='дата последнего обслуживания',
        help_text='Дата последнего обслуживания пожарной сигнализации на объекте.'
    )

    next_service_date = models.DateField(
        verbose_name='дата следующего обслуживания',
        help_text='Дата следующего обслуживания пожарной сигнализации на объекте.',
        blank=True,
        null=True
    )

    photo = models.ImageField(
        verbose_name='фото объекта',
        help_text='Фотография объекта, на котором установлена пожарная сигнализация.',
        blank=True,
        null=True,
        upload_to='service_photos/'
    )

    address = models.ForeignKey(
        Address,
        on_delete=models.CASCADE,
        verbose_name='Адрес объекта',
        related_name='fire_alarm_objects')

    branch = models.ForeignKey(
        Branch,
        on_delete=models.CASCADE,
        verbose_name='филиал',
        help_text='Филиал, к которому относится данный объект.',
        related_name='fire_alarm_objects'
    )

    service_zone = models.ForeignKey(
        ServiceZone,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="Зона обслуживания",
        related_name="fire_alarm_objects")

    service_organizations = models.ForeignKey(
        ServiceOrganizations,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        verbose_name="Обслуживающия организация",
        related_name="fire_alarm_objects"
    )

    remote_number = models.CharField(verbose_name='Пультовый номер',
                                     max_length=20,
                                      blank=True,
                                      null=True)

    room_number = models.CharField(verbose_name='Помещение',
                                   max_length=50,
                                   blank=True,
                                   null=True)
    contract_number = models.CharField(verbose_name='Номер договора',
                                       max_length=50,
                                       blank=True,
                                       null=True)
    contract_date = models.DateField(
        verbose_name='Дата заключения договора',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'объект'
        verbose_name_plural = 'объекты'

    def save(self, *args, **kwargs):
        if not self.photo:
            default_image_path = os.path.join(MEDIA_ROOT, 'default_image.jpg')
            with open(default_image_path, 'rb') as f:
                default_image = File(f)
                self.photo.save('default_image.jpg', default_image, save=False)
        if not self.last_service_date:
            self.last_service_date = timezone.now().date()
        if not self.next_service_date:
            if self.frequency == 'Ежемесячно':
                self.next_service_date = self.last_service_date + \
                    relativedelta(months=1)
            elif self.frequency == 'Ежеквартально':
                self.next_service_date = self.last_service_date + \
                    relativedelta(months=3)
        super().save(*args, **kwargs)

    def update_next_service_date(self):
        if self.frequency == 'Ежемесячно':
            self.next_service_date = self.last_service_date + \
                relativedelta(months=1)
        elif self.frequency == 'Ежеквартально':
            self.next_service_date = self.last_service_date + \
                relativedelta(months=3)
        self.save()

    def __str__(self):
        return self.name

    def auto_add_service_zone(self):
        geopoint = Point(eval(self.address.get_geopoint()))
        zones = ServiceZone.objects.filter(branch=self.branch)
        for zone in zones:
            if Polygon(eval(zone.geopoints)).contains(geopoint):
                self.service_zone = zone
                self.save()
                return True
        return False


class FireAlarmObjectService(models.Model):
    """
    Модель технического обслуживания пожарной сигнализации
    """
    fire_alarm_object = models.ForeignKey(
        FireAlarmObject, on_delete=models.CASCADE, verbose_name='Объект', related_name='service_done')
    service_date = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата создания')
    technician = models.ForeignKey(
        Technician, blank=True,
        null=True, on_delete=models.PROTECT, verbose_name='Техник', related_name='service_done')
    service_journal_title_page_photo = models.ImageField(
        upload_to='service_photos/', 
        verbose_name='Фотография обложки журнала техобслуживания ПС',
        blank=True, 
        default='media/default_image.jpg'
    )
    service_journal_photo = models.ImageField(
        upload_to='service_photos/', verbose_name='Фотография журнала техобслуживания ПС')
    control_panel_photo = models.ImageField(
        upload_to='service_photos/', verbose_name='Фотография головного прибора ПС')
    comment = models.TextField(blank=True, verbose_name='Комментарий')

    class Meta:
        verbose_name = 'Обслуживание объекта'
        verbose_name_plural = 'Обслуживания объектов'

    def save(self, *args, **kwargs):
        # при сохранении устанавливаем last_service_date на текущую дату у связанного объекта
        self.fire_alarm_object.last_service_date = timezone.now()
        self.fire_alarm_object.update_next_service_date()
        pending_failed_services = FailedService.objects.filter(
            fire_alarm_object=self.fire_alarm_object, status__in=['pending', 'in_progress'])
        for failed_service in pending_failed_services:
            failed_service.status = 'completed'
            failed_service.save()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Обслуживание {self.fire_alarm_object} от {self.service_date}'


class FailedService(models.Model):
    """
    Модель неудавшегося обслуживания пожарной сигнализации
    """
    status_choices = [
        ('pending', 'В ожидании'),
        ('in_progress', 'Выполняется'),
        ('completed', 'Завершено'),
    ]
    technician = models.ForeignKey(
        Technician, on_delete=models.PROTECT, verbose_name='Техник', related_name='failed_services')
    status = models.CharField(choices=status_choices,
                              max_length=255, default='pending')
    service_date = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата создания')
    fire_alarm_object = models.ForeignKey(
        FireAlarmObject, on_delete=models.CASCADE, related_name='failed_services')
    photo = models.ImageField(
        upload_to='failed_service_photos/', verbose_name='Фото неисправности', blank=True,
        null=True,)

    comment = models.TextField(verbose_name='Комментарий')
    
    class Meta:
        verbose_name = 'Проблема с обслуживания'
        verbose_name_plural = 'Проблемы с обслуживаниями'
        
    def __str__(self):
        return f"{self.fire_alarm_object} - {self.service_date }"

tasker/service_zone/models.py
from django.db import models
from branch.models import Branch
from technicians.models import Technician


class ServiceZone(models.Model):
    """
    Модель зоны обслуживания.
    """

    name = models.CharField(
        verbose_name='название',
        help_text='Название зоны обслуживания.',
        max_length=100
    )

    description = models.TextField(
        verbose_name='описание',
        help_text='Подробное описание зоны обслуживания.',
        blank=True
    )

    branch = models.ForeignKey(
        Branch,
        on_delete=models.CASCADE,
        verbose_name='филиал',
        help_text='Филиал, к которому относится зона обслуживания.'
    )

    class Meta:
        verbose_name = 'зона обслуживания'
        verbose_name_plural = 'зоны обслуживания'


class TechnicianZone (models.Model):
    technician = models.ForeignKey(
        Technician,
        verbose_name='техник',
        related_name='service_zones',
        on_delete=models.CASCADE
    )
    service_zone = models.ForeignKey(
        ServiceZone,
        verbose_name='зоны обслуживания',
        related_name='technicians',
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = 'Зона техника'
        verbose_name_plural = 'Зоны техников'
        constraints = (
            models.UniqueConstraint(
                fields=['technician', 'service_zone'], name='unique_follow'),
        )

tasker/fire_alarm_objects/views.py
from django.shortcuts import render

# Create your views here.

tasker/templates/engineers/create_service_zone.html
{% extends 'base.html' %}
{% block sidebarMenu %}
  {% include 'engineers/includes/sidebarMenu.html' %}
{% endblock sidebarMenu %}

{% block content %}
    <div class="row">
      <div class="col-md-8 col-lg-9">
        <div id="map"></div>
        <script>
            ymaps.ready(init);
            
            function init() {
                var myMap = new ymaps.Map("map", {
                        center: {{branch_location}},
                        zoom: 10
                    }, {
                        searchControlProvider: 'yandex#search'
                    });
        
                       
                {% for zone in zones %}
                    // Получаем координаты зоны из поля geopoints модели ServiceZone
                    var coordinates{{zone.id}} = {{ zone.geopoints }};
        
                    // Создаем многоугольник на карте
                    var Polygon{{zone.id}} = new ymaps.Polygon([coordinates{{zone.id}}], {
                        hintContent: "{{ zone.name }}"
                    }, {
                        fillColor: '{{ zone.color }}',
                        strokeColor: '#0000FF',
                        strokeOpacity: 0.5,
                        strokeWidth: 2
                    });
                    
                    
                    // Добавляем многоугольник на карту
                    myMap.geoObjects.add(Polygon{{zone.id}});
                {% endfor %}
                // Создаем многоугольник без вершин.
                {% if form.errors %}
                  var coordinates = {{ form.data.geopoints}}
                {% elif is_edit %}
                  var coordinates = {{ form.initial.geopoints}}
                {% else %}
                  var coordinates = []
                {% endif %}
                
                var myPolygon = new ymaps.Polygon([coordinates], {}, {
                    // Курсор в режиме добавления новых вершин.
                    editorDrawingCursor: "crosshair",
                    // Максимально допустимое количество вершин.
                    editorMaxPoints: 200,
                    // Цвет заливки.
                    fillColor: '#00FF0099',
                    // Цвет обводки.
                    strokeColor: '#0000FF',
                    // Ширина обводки.
                    strokeWidth: 2
                });
                // Добавляем многоугольник на карту.
                myMap.geoObjects.add(myPolygon);
            
                // В режиме добавления новых вершин меняем цвет обводки многоугольника.
                var stateMonitor = new ymaps.Monitor(myPolygon.editor.state);
                stateMonitor.add("drawing", function (newValue) {
                    myPolygon.options.set("strokeColor", newValue ? '#FF0000' : '#0000FF');
                });
            
                // Включаем режим редактирования с возможностью добавления новых вершин.
                myPolygon.editor.startDrawing();
        
                document.getElementById('add_zone').addEventListener('click', function () {
                    // Получаем координаты вершин многоугольника
        
        
                    var coordinates = myPolygon.geometry.getCoordinates()[0];
                    
        
                    // Заполняем скрытое поле формы с координатами многоугольника
                    document.getElementById('id_geopoints').value = JSON.stringify(coordinates);
                    
                    // Отправляем данные на сервер
                    var xhr = new XMLHttpRequest();
                    xhr.open('POST', '{% url "engineers:create_service_zone" %}');
                    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                    xhr.onreadystatechange = function () {
                        if (xhr.readyState === 4 && xhr.status === 200) {
                            alert('Зона добавлена');
                        }
                    };
                    xhr.send(new FormData(document.getElementById('polygon-form')));
                });
            }
        </script>
      </div>
      <div class="col-md-4 col-lg-3 scrollable">
        <p>
        <div class="card">
            <div class="card-header">       
                {% if is_edit %}
                Редактировать запись
                {% else %}
                Добавить запись
                {% endif %}           
            </div>
            <div class="card-body">
                {% if form.errors %}
                
                {% for field in form %}
                  {% for error in field.errors %}            
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
                {% endif %}
              {% if is_edit %}
                <form id="polygon-form" method="POST" action="{% url 'engineers:service_zone_edit' zone.id %}">
              {% else %}
                <form id="polygon-form" method="POST" action="{% url 'engineers:create_service_zone' %}">
              {% endif %}
                {% csrf_token %}                     
                <input type="hidden" name="geopoints" value="{% if is_edit %}{{form.initial.geopoints}}{% endif %}" id="id_geopoints">                          
                <div class="form-group row my-3 p-3">
                  <label for="id_name">
                    Название                                           
                       <span class="required text-danger">*</span>                                         
                  </label>
                  <input type="text" name="name" value="{% if is_edit %}{{form.initial.name}}{% endif %}" maxlength="100" required="" id="id_name">                                     
                    <small id="id_name-help" class="form-text text-muted">
                      Название зоны обслуживания.
                    </small>                    
                </div>    
                <div class="form-group row my-3 p-3">
                  <label for="id_description">
                    Описание  
                  </label>
                  <textarea name="description" value="{% if is_edit %}{{form.initial.description}}{% endif %}" cols="40" rows="10" id="id_description"></textarea>    
                    <small id="id_description-help" class="form-text text-muted">
                      Подробное описание зоны обслуживания.
                    </small>                 
                </div>       
                <button id="add_zone">Сохранить зону</button>
              </form>
            </div>
        </div>
      </div>
    </div>
{% endblock content %}

tasker/templates/engineers/fire_alarm_object_detail.html
{% extends 'base.html' %}
{% block sidebarMenu %}
  {% include 'engineers/includes/sidebarMenu.html' %}
{% endblock sidebarMenu %}

{% block content %}
<div class='container'>
  <div class="row">
    <div class="col-md-6">
      {% include 'engineers/fire_alarm_object/includes/fire_alarm_object_info.html' %}
    </div>
    <div class="col-md-6">
      {% include 'engineers/fire_alarm_object/fire_alarm_object_services.html' %}
      {% include 'engineers/fire_alarm_object/fire_alarm_object_failed_services.html' %}
    </div>
  </div>
</div>
{% endblock %}

tasker/templates/engineers/fire_alarm_objects.html
{% extends 'base.html' %}
{% block sidebarMenu %}
  {% include 'engineers/includes/sidebarMenu.html' %}
{% endblock sidebarMenu %}
{% load thumbnail %}
{% block content %}
<div class='container'>
  <div class="row">
    <div class="col-md-6">
        {% include 'engineers/fire_alarm_object/includes/fire_alarm_object_filter.html' %}
        {% include 'engineers/fire_alarm_object/fire_alarm_objects_list.html' %}
    </div> 
    <div class="col-md-6">
      <div class='card mt-1 mb-1'>
        <div class = 'card-body'>
            <a href="{% url 'engineers:create_fire_alarm_object' %}" type ="bottom" class="btn btn-success">Создать объект обслуживания</a>
            <a href="{% url 'engineers:import_csv' %}" class="btn btn-secondary">Импортировать список</a>
        </div>
      </div>
      <div class='card mt-1 mb-1 'style=' max-height: 490px;'>
        {% include 'engineers/includes/base_map.html' %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

tasker/templates/engineers/import_csv.html
{% extends 'base.html' %}

{% block content %}
  <h1>Импорт данных из CSV</h1>
  {% if success_count %}
    <p>Успешно создано {{ success_count }} записей</p>
  {% endif %}
  {% if error_count %}
    <p>Не удалось создать {{ error_count }} записей</p>
  {% endif %}
  {% for error in error_list %}
    <p>{{ error}}</p>
  {% endfor %}
  {% if double_count %}
    <p>Дубли :{{double_count}} </p>
  {% endif %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="csv_file">Файл CSV:</label>
    <input type="file" name="csv_file" required>
    <br>
    <button type="submit">Импортировать</button>
  </form>
{% endblock %}

tasker/templates/engineers/index.html
{% extends 'base.html' %}
{% block sidebarMenu %}
  {% include 'engineers/includes/sidebarMenu.html' %}
{% endblock sidebarMenu %}

{% block content %}
<div class ='conteiner'>
  <div class='conteiner mt-1 mb-1'>
    {% if fire_alarm_objects_without_zone %}
      <button class="btn btn-danger btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#fire_alarm_objects_without_zone" aria-expanded="false" aria-controls="fire_alarm_objects_without_zone">
        Объекты без назначеных зон
      </button>
    {% endif %}
    {% if service_zone_without_technician %}
      <button class="btn btn-danger btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#service_zone_without_technician" aria-expanded="false" aria-controls="service_zone_without_technician">
        Зоны без назначеных техников
      </button>
    {% endif %}
    {% if technician_without_zone %}
      <button class="btn btn-danger btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#technician_without_zone" aria-expanded="false" aria-controls="technician_without_zone">
        Техники без назначеных зон
      </button>
    {% endif %}
      <div class="collapse" id="fire_alarm_objects_without_zone">
        <div class='card-body'style='overflow:auto; max-height: 500px;'>
          {% for fire_alarm_object in fire_alarm_objects_without_zone %}
            {% include 'engineers/fire_alarm_object/includes/fire_alarm_object_info.html' %}
            {% empty %}
            <p>Нет объектов для отображения.</p>
          {% endfor %}
        </div>
      </div>
      <div class="collapse" id="service_zone_without_technician">
        <div class='card-body'style='overflow:auto; max-height: 500px;'>
          {% for service_zone in service_zone_without_technician %}
            {% include 'engineers/service_zone/includes/service_zone_info.html' %}
            {% empty %}
            <p>Нет объектов для отображения.</p>
          {% endfor %}
        </div>
      </div>
      <div class="collapse" id="technician_without_zone">
        <div class='card-body'style='overflow:auto; max-height: 500px;'>
          {% for technician in technician_without_zone %}
            {% include 'engineers/technician/technician_info.html' %}
            {% empty %}
            <p>Нет объектов для отображения.</p>
          {% endfor %}
        </div>
      </div>
  </div>
  <div class='conteiner'>
    {% if fire_alarm_failed_services %}
      <div class="accordion" id="accordion-service_zones">
        <div class="card mb-1 mt-1" >
          <div class= 'card-header'>
            <h5>Проблемные обслуживания</h5>
          </div>
          <div class='card-body'style='overflow:auto; max-height: 500px;'>
            {% for fire_alarm_failed_service in fire_alarm_failed_services %}
              {% include 'engineers/includes/fire_alarm_failed_service.html' %}
            {% endfor %}
          </div>
        </div>  
      </div>
    {% endif %}
    {% if fire_alarm_services %}
      <div class="card mb-1 mt-1" >
        <div class='card-header'>
          <h5>События</h5>
        </div>
        <div class='card-body'style='overflow:auto; max-height: 500px;'>
          {% for fire_alarm_service in fire_alarm_services %}
            {% include 'engineers/includes/fire_alarm_service.html' %}
          {% endfor %}
        </div>
      </div>
    {% endif %}
  </div>
</div>  
{% endblock content %}

tasker/templates/engineers/service_zone_detail.html
{% extends 'base.html' %}
{% block sidebarMenu %}
  {% include 'engineers/includes/sidebarMenu.html' %}
{% endblock sidebarMenu %}
{% load user_filters %}
{% block content %}
<div class="row">
    <div class="col-md-6 ">
      {% include 'engineers/service_zone/includes/service_zone_info.html' %}
      {% include 'engineers/fire_alarm_object/fire_alarm_objects_list.html' %}

    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          {% include 'engineers/includes/base_map.html'%}
        </div>
      </div>
    </div>
</div>


{% endblock content %}

tasker/templates/engineers/service_zones.html
{% extends 'base.html' %}
{% block sidebarMenu %}
  {% include 'engineers/includes/sidebarMenu.html' %}
{% endblock sidebarMenu %}
{% load user_filters %}
{% block content %}
<div class = 'col-md-12 mt-1 mb-1'>
  {% include 'engineers/service_zone/service_zone_top_menu.html' %}
</div>
<div class="row">
    <div class="col-md-6 ">
      <div class="card">
        <div class="card-body">
          {% include 'engineers/includes/base_map.html'%}
        </div>
      </div>
    </div>
    <div class="col-md-6">
      {% include 'engineers/service_zone/service_zones.html' %}
    </div>
</div>


{% endblock content %}