tasker/engineers/urls.py
from django.urls import path


from . import views

app_name = 'engineers'

urlpatterns = [
    path('', views.index,
         name='index'),
    path('service_zones/', views.service_zones, name='service_zones'),
    path('create_service_zone/', views.create_service_zone,
         name='create_service_zone'),
    path('service_zone/<int:service_zone_id>/delete/',
         views.service_zone_delete, name='service_zone_delete'),
    path('service_zone/<int:service_zone_id>/edit/',
         views.service_zone_edit, name='service_zone_edit'),
     path('service_zone/<int:service_zone_id>/deteil/',
         views.service_zone_deteil, name='service_zone_deteil'),
    path('technicians/', views.technicians, name='technicians'),
    path('technician/<int:technician_id>/detail/',
         views.technician_detail, name='technician_detail'),
    path('technician/<int:technician_id>/activate/',
         views.technician_activate, name='technician_activate'),
    path('technician/<int:technician_id>/deactivate/',
         views.technician_deactivate, name='technician_deactivate'),
    path('technician_zone/<int:technician_zone_id>/delete/',
         views.technician_zone_delete, name='technician_zone_delete'),
    path('fire_alarm_objects/', views.fire_alarm_objects,
         name='fire_alarm_objects'),
    path('fire_alarm_objects/<int:to_date>/', views.fire_alarm_objects_filter,
         name='fire_alarm_objects_filter'),
    path('fire_alarm_object/create/', views.create_fire_alarm_object,
         name='create_fire_alarm_object'),
    path('fire_alarm_object/<int:object_id>/edite/',
         views.fire_alarm_object_edite, name='fire_alarm_object_edite'),
    path('fire_alarm_object/<int:object_id>/delete/',
         views.fire_alarm_object_delete, name='fire_alarm_object_delete'),
    path('fire_alarm_object/<int:object_id>/detail/', views.fire_alarm_object_detail, name = 'fire_alarm_object_detail'),
    path('import_csv/', views.import_csv, name ='import_csv')
]

tasker/tasker/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from users import views
from django.urls import reverse_lazy
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('engineers/', include('engineers.urls', namespace='engineers')),
    path('technicians/', include('technicians.urls', namespace='technicians.urls')),

    #################### Регистрация, и смена пароля##########################
    path('login', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('signup/', views.SignUp.as_view(template_name='users/signup.html'),
         name='signup'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        success_url=reverse_lazy('password_reset_done')
    ), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('password_reset_complete')
    ), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change_form.html'),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),
    ##########################################################

    path('', include('users.urls', namespace='users')),

]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

tasker/technicians/urls.py
from django.urls import path


from . import views

app_name = 'technicians'

urlpatterns = [
    path('', views.index,
         name='index'),
    path('tasks/<int:to_date>/show/',
         views.tasks, name='tasks'),
    path('fire_alarm_objects/<int:to_date>/show/',
         views.fire_alarm_objects, name='fire_alarm_objects'),
    path('fire_alarm_object_service/<int:object_id>/create/',
         views.fire_alarm_object_service_create, name='fire_alarm_object_service_create'),
    path('fire_alarm_object_service/<int:object_id>/detail', views.fire_alarm_object_service_detail , name='fire_alarm_object_service_detail'),
    path('failed_service/<int:object_id>/create',views.failed_service_create, name= 'failed_service_create')
]

tasker/users/urls.py
from django.urls import path


from . import views

app_name = 'users'

urlpatterns = [
    path('account_not_confirmed/', views.account_not_confirmed,
         name='account_not_confirmed'),
    path('', views.division_users,
         name='index'),
]

tasker/engineers/models.py
from django.db import models
from django.contrib.auth import get_user_model
from branches.models import Branch
User = get_user_model()


class Engineer(models.Model):
    """
    Модель для хранения информации об инженерах.
    """
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name='пользователь',
        help_text='Пользователь, к которому относится инженер',
    )
    branch = models.ForeignKey(
        Branch,
        on_delete=models.CASCADE,
        verbose_name='филиал',
        help_text='Выберите филиал, к которому относится инженер'
    )
    is_active = models.BooleanField(
        default=False,
        verbose_name='активен',
        help_text='Укажите, активена ли учетная запись инженер',
    )
    last_name = models.CharField(
        max_length=30,
        verbose_name='фамилия',
        help_text='Фамилия инженера',
    )
    first_name = models.CharField(
        max_length=30,
        verbose_name='имя',
        help_text='Имя инженера',
    )
    middle_name = models.CharField(
        max_length=30,
        verbose_name='отчество',
        help_text='Отчество инженера',
    )
    phone = models.CharField(
        max_length=20,
        verbose_name='телефон',
        help_text='Телефон инженера',
    )
    photo = models.ImageField(
        upload_to='engineer_photos',
        blank=True,
        null=True,
        verbose_name='фото',
        help_text='Фото инженера',
    )

    class Meta:
        verbose_name = 'инженер'
        verbose_name_plural = 'инженеры'

    def __str__(self):
        return f"{self.last_name} {self.first_name} {self.middle_name}"

tasker/engineers/views.py
from django.shortcuts import render
from service_zones.forms import ServiceZoneForm, AssignZonesForm, AssignZoneToObjectForm
from .models import Engineer
from django.shortcuts import get_object_or_404, redirect
from service_zones.models import ServiceZone, TechnicianZone
from core.decorators.user_decorators import engineer_required
from django.db.models import Q
from technicians.models import Technician
from fire_alarm_objects.models import FireAlarmObject
from fire_alarm_objects.forms import FireAlarmObjectForm
from shapely.geometry import Polygon
import csv
from django.shortcuts import render
from core.tools.tools_for_addrees import clean_address, clean_date
from service_оrganizations.models import ServiceOrganizations
from django.db.models import Prefetch
from .tools.objects import get_fire_alarm_objects
from core.tools.tools import days_left_in_month
from fire_alarm_objects.models import FailedService, FireAlarmObject, FireAlarmObjectService
from service_zones.utils import add_fire_alarm_zone


@engineer_required
def index(request):
    engineer = get_object_or_404(Engineer, user=request.user)
    fire_alarm_services = FireAlarmObjectService.objects.filter(
        technician__branch=engineer.branch)
    fire_alarm_failed_services = FailedService.objects.filter(
        technician__branch=engineer.branch)
    fire_alarm_objects_without_zone = FireAlarmObject.objects.filter(
        branch=engineer.branch, service_zone=None)
    technician_without_zone = Technician.objects.filter(
        branch=engineer.branch, service_zones=None)
    service_zone = ServiceZone.objects.filter(branch=engineer.branch)
    service_zone_without_technician = ServiceZone.objects.filter(
        branch=engineer.branch, technicians=None)
    fire_alarm_objects = FireAlarmObject.objects.select_related(
        'address').filter(branch=engineer.branch)
    branch_location = engineer.branch.get_location()
    template = 'engineers/index.html'
    context = {'service_zone': service_zone,
               'branch_location': branch_location,
               'objects': fire_alarm_objects,
               'fire_alarm_services': fire_alarm_services,
               'fire_alarm_failed_services': fire_alarm_failed_services,
               'fire_alarm_objects_without_zone': fire_alarm_objects_without_zone,
               'technician_without_zone': technician_without_zone,
               'service_zone_without_technician': service_zone_without_technician,
               'index': True}
    return render(request, template_name=template, context=context)


@engineer_required
def service_zones(request):
    engineer = get_object_or_404(Engineer, user=request.user)
    service_zones = ServiceZone.objects.filter(branch=engineer.branch)
    fire_alarm_objects = FireAlarmObject.objects.select_related(
        'address').filter(branch=engineer.branch)
    branch_location = engineer.branch.get_location()
    template = 'engineers/service_zones.html'

    context = {'service_zones': service_zones,
               'branch_location': branch_location,
               'fire_alarm_objects': fire_alarm_objects}
    return render(request, template_name=template, context=context)


@engineer_required
def service_zone_deteil(request, service_zone_id):
    service_zone = get_object_or_404(ServiceZone, id=service_zone_id)
    fire_alarm_objects = FireAlarmObject.objects.filter(
        service_zone=service_zone)
    technicians = Technician.objects.filter(
        service_zones__service_zone_id=service_zone_id)
    template = "engineers/service_zone_detail.html"
    context = {'service_zone': service_zone,
               'fire_alarm_objects': fire_alarm_objects,
               'technicians': technicians}
    return render(request, template, context)


@engineer_required
def create_service_zone(request):
    engineer = get_object_or_404(Engineer, user=request.user)
    zones = ServiceZone.objects.filter(branch=engineer.branch)
    branch_location = engineer.branch.get_location()
    form = ServiceZoneForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        service_zone = form.save(commit=False)
        service_zone.geopoints = form.cleaned_data['geopoints']
        service_zone.branch = engineer.branch
        service_zone.save()
        add_fire_alarm_zone(service_zone)

        return redirect('engineers:service_zones')

    return render(request,
                  'engineers/create_service_zone.html',
                  {'form': form,
                   'zones': zones,
                   'branch_location': branch_location})


@engineer_required
def service_zone_edit(request, service_zone_id):
    zone = get_object_or_404(ServiceZone, id=service_zone_id)
    zones = ServiceZone.objects.filter(Q(branch=zone.branch) & ~Q(id=zone.id))
    engineer = get_object_or_404(Engineer, user=request.user)
    branch_location = engineer.branch.get_location()
    template_create = 'engineers/create_service_zone.html'
    form = ServiceZoneForm(request.POST or None, instance=zone)
    if form.is_valid():
        service_zone = form.save()
        add_fire_alarm_zone(service_zone)
        return redirect('engineers:service_zones')
    context = {
        'form': form,
        'is_edit': True,
        'zones': zones,
        'zone': zone,
        'branch_location': branch_location
    }

    return render(request, template_create, context)


@engineer_required
def service_zone_delete(request, service_zone_id):
    service_zone = get_object_or_404(ServiceZone, id=service_zone_id)
    service_zone.delete()
    return redirect('engineers:service_zones')


def get_full_technicians(branch):
    technicians = Technician.objects.filter(branch=branch)
    result = []
    for technician in technicians:
        service_zones = ServiceZone.objects.filter(
            technicians__technician_id=technician.id)
        fire_alarm_objects = FireAlarmObject.objects.select_related(
            'address').filter(service_zone__technicians__technician_id=technician.id)
        result.append({
            'technician': technician,
            'service_zones': service_zones,
            'fire_alarm_objects': fire_alarm_objects,
            'branch_location': technician.branch.get_location()
        })
    return result


@engineer_required
def technicians(request):
    engineer = get_object_or_404(Engineer, user=request.user)
    technicians = get_full_technicians(branch=engineer.branch)
    template = 'engineers/technicians.html'
    context = {'technicians_obj_list': technicians,
               'show_map': True}
    return render(request, template, context)


@engineer_required
def technician_activate(request, technician_id):
    technician = get_object_or_404(Technician, id=technician_id)
    technician.is_active = True
    technician.save()
    return redirect('engineers:technician_detail', technician_id)


@engineer_required
def technician_deactivate(request, technician_id):
    technician = get_object_or_404(Technician, id=technician_id)
    technician.is_active = False
    technician.save()
    return redirect('engineers:technician_detail', technician_id)


@engineer_required
def assign_zones(request, technician_id):
    technician = Technician.objects.get(id=technician_id)
    if request.method == 'POST':
        form = AssignZonesForm(technician, request.POST)
        if form.is_valid():
            form.save()
            return redirect('technician_detail', technician_id=technician_id)
    else:
        form = AssignZonesForm(technician)
    return render(request, 'assign_zones.html', {'form': form, 'technician': technician})


@engineer_required
def technician_detail(request, technician_id):
    technician = get_object_or_404(Technician, id=technician_id)
    technician_zones = TechnicianZone.objects.filter(technician=technician)
    fire_alarm_objects = FireAlarmObject.objects.select_related(
        'address').filter(
        service_zone__technicians__technician_id=technician.id)
    service_zones = ServiceZone.objects.filter(
        technicians__technician_id=technician.id)
    if request.method == 'POST':
        form = AssignZonesForm(technician, request.POST)
        if form.is_valid():
            form.save()
            return redirect('engineers:technician_detail', technician_id)
    form = AssignZonesForm(technician)
    return render(request, 'engineers/technician.html', {'technician': technician,
                                                         'branch_location': technician.branch.get_location(),
                                                         'form': form,
                                                         'technician_zone': technician_zones,
                                                         'service_zones': service_zones,
                                                         'fire_alarm_objects': fire_alarm_objects,
                                                         'show_info': True})


@engineer_required
def technician_zone_delete(request, technician_zone_id):
    technician_zone = TechnicianZone.objects.select_related(
        'technician').get(id=technician_zone_id)
    technician_id = technician_zone.technician.id
    technician_zone.delete()
    return redirect('engineers:technician_detail', technician_id)


@engineer_required
def fire_alarm_objects(request):
    fire_alarm_objects = FireAlarmObject.objects.all()
    engineer = get_object_or_404(Engineer, user=request.user)
    branch_location = engineer.branch.get_location()
    service_zones = ServiceZone.objects.filter(branch=engineer.branch)
    context = {'fire_alarm_objects': fire_alarm_objects,
               'branch_location': branch_location,
               'service_zones': service_zones,
               'days_left_in_month': days_left_in_month()}
    template = 'engineers/fire_alarm_objects.html'
    return render(request, template, context)


@engineer_required
def fire_alarm_objects_filter(request, to_date=None):

tasker/templates/engineers/includes/base_map.html
{% load user_filters %}
<div class="card mt-1 mb-1">
  <div id="map"></div>
  <script type="text/javascript">
      ymaps.ready(init);
      function init() {
          var myMap = new ymaps.Map("map", {
              center: {{branch_location}},
              zoom: 10
          });
          {% for zone in service_zones %}
              // Получаем координаты зоны из поля geopoints модели ServiceZone
              var coordinates = {{ zone.geopoints }};
  
              // Создаем многоугольник на карте
              var myPolygon = new ymaps.Polygon([coordinates], {
                  hintContent: "{{ zone.name }}"
              }, {
                  fillColor: '{{ zone.color}}',
                  strokeColor: '#0000FF',
                  strokeOpacity: 0.5,
                  strokeWidth: 2
              });
  
              // Добавляем многоугольник на карту
              myMap.geoObjects.add(myPolygon);
          {% endfor %}
          {% for object in fire_alarm_objects %}
          var placemark{{object.id}} = new ymaps.Placemark(
              {{ object.address.get_geopoint }}, {
                  balloonContentHeader: '<h5>{{object.name}}</h5><br>',
                  balloonContentBody: 
                  '<div class = "row">'+
                  '<div class="container">'+
                  '<p class="card-text"><h6>Обслуживающая организация:</h6> {{ object.service_organizations }}</p>'+
                  '<p class="card-text"><h6>Переодичность:</h6> {{ object.frequency }}</p>'+
                  '<p class="card-text"><h6>Произвести обслуживания до:</h6> {{ object.next_service_date }}</p>'+
                  '</div>'+
                  '</div>',
                  balloonContentFooter: '<div class="d-grid gap-3">'+
                      '<button class="btn btn-warning btn-sm" type="button">Построить маршрут</button>'+
                      '<a href = "{% url "technicians:fire_alarm_object_service_detail" object.id %} " class="btn btn-primary btn-sm" >Карточка объекта</a>'+
                      '</div>',
                  hintContent: '{{object.name}}'
              },{
                  preset: 'islands#dotIcon',
                  iconColor: '{{object|map_icon_color}}'
              });
  
  
          {% endfor %}
  
          myMap.geoObjects
              {% for object in fire_alarm_objects %}
              .add(placemark{{object.id}})
              {% endfor %};      
      }
  </script>
</div>

tasker/templates/engineers/includes/fire_alarm_failed_service.html
{% load thumbnail %}
<div class="accordion" id="accordion-fire_alarm_failed_service{{fire_alarm_failed_service.id}}">
    <div class="card mb-1 mt-1" >
      <div class="card-body"  data-bs-toggle="collapse" data-bs-target="#collapse-fire_alarm_failed_service{{fire_alarm_failed_service.id}}"  aria-controls="collapse-fire_alarm_failed_service{{fire_alarm_failed_service.id}}">
        <div class ='row'>  
          <div class="col-md-6">
            <h5>{{fire_alarm_failed_service}}</h5>
          </div>
        </div>
      </div>
      <div id="collapse-fire_alarm_failed_service{{fire_alarm_failed_service.id}}" class="accordion-collapse collapse" aria-labelledby="heading-fire_alarm_failed_service{{fire_alarm_failed_service.id}}" data-bs-parent="#accordion-fire_alarm_failed_service{{fire_alarm_failed_service.id}}">
        <div class="row">
          <div class="col-md-6 col-sm-12">
            <div class="card-body">
              {{ fire_alarm_failed_service.fire_alarm_object }}
              {{ fire_alarm_failed_service.fire_alarm_object.address}}
              <p class="card-text">Произвел обслуживание: {{ fire_alarm_failed_service.technician }}</p>
              <p class="card-text">Коментарий: {{ fire_alarm_failed_service.comment }}</p>
              <div class='row'>
                <div class='col-6'>
                  <p class="card-text">Фото</p>
                  {% if  fire_alarm_failed_service.photo %}
                    {% thumbnail fire_alarm_failed_service.photo "90x90" crop="center" as photo %}
                      <a href="{{ fire_alarm_failed_service.photo.url }}"><img class="img-thumbnail float-end" src="{{ photo.url }}"></a>
                    {% endthumbnail %}
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

tasker/templates/engineers/includes/fire_alarm_service.html
{% load thumbnail %}
<div class="accordion" id="accordion-fire_alarm_service{{fire_alarm_service.id}}">
    <div class="card mb-1 mt-1" >
      <div class="card-body"  data-bs-toggle="collapse" data-bs-target="#collapse-fire_alarm_service{{fire_alarm_service.id}}"  aria-controls="collapse-fire_alarm_service{{fire_alarm_service.id}}">
        <div class ='row'>  
          <div class="col-md-6">
            <h5>Обслуживание {{fire_alarm_sevice.fire_alarm_object}} от {{fire_alarm_service.service_date}}</h5>
          </div>
        </div>
      </div>
      <div id="collapse-fire_alarm_service{{fire_alarm_service.id}}" class="accordion-collapse collapse" aria-labelledby="heading-fire_alarm_service{{fire_alarm_service.id}}" data-bs-parent="#accordion-fire_alarm_service{{fire_alarm_service.id}}">
        <div class="row">
          <div class="col-md-6 col-sm-12">
            <div class="card-body">
              <p class="card-text">Произвел обслуживание: {{ fire_alarm_service.technician }}</p>
              <p class="card-text">Коментарий: {{ fire_alarm_service.comment }}</p>
              <div class='row'>
                <div class='col-6'>
                  <p class="card-text">Фото журнала<p>
                  {% if  fire_alarm_service.service_journal_photo %}
                    {% thumbnail fire_alarm_service.service_journal_photo "90x90" crop="center" as service_journal_photo %}
                      <a href="{{ fire_alarm_service.service_journal_photo.url }}"><img class="img-thumbnail float-end" src="{{ service_journal_photo.url }}"></a>
                    {% endthumbnail %}
                  {% endif %}
                </div>
                <div class='col-6'>
                  <p class="card-text">Фото панели<p>
                  {% if fire_alarm_service.control_panel_photo %}
                    {% thumbnail fire_alarm_service.control_panel_photo  "90x90" crop="center" as control_panel_photo %}
                      <a href="{{ fire_alarm_service.control_panel_photo.url }}"><img class="img-thumbnail float-end" src="{{ control_panel_photo.url }}"></a>
                    {% endthumbnail %}
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

tasker/templates/engineers/includes/sidebarMenu.html
<div class="accordion" id="accordion-sidebarMenu">
  <div class="card">
    <div class="card-body"  data-bs-toggle="collapse" data-bs-target="#collapse-sidebarMenu" aria-expanded="true" aria-controls="collapse-sidebarMenu">
  
      <li class="list-group-item">Меню</li>

    </div>
    <div id="collapse-sidebarMenu" class="accordion-collapse collapse show" aria-labelledby="heading-sidebarMenu" data-bs-parent="#accordion-sidebarMenu">
      <ul class="list-group list-group-flush">
        <a class="list-group-item" type='button' href="{% url 'engineers:index' %}">Главная</a>
        <a class="list-group-item" type='button' href="{% url 'engineers:service_zones' %}">Зоны обслуживания ПС</a>
        <a class="list-group-item" type='button' href="{% url 'engineers:technicians' %}">Техники</a>
        <a class="list-group-item" type='button' href="{% url 'engineers:fire_alarm_objects' %}">Объекты</a>
      </ul>
    </div>
  </div>
</div>

tasker/templates/engineers/includes/technician_without_zone.html
<div class="accordion" id="accordion-service_zone_without_technician">
    <div class="card mb-1 mt-1" >
      <div class='card-body'style='overflow:auto; max-height: 500px;'>
        <p class='card-text'><h5>Объекты без зон</h5></p>
        {% for technician in technician_without_zone %}
          {% include 'engineers/technician/technician_info.html' %}
          {% empty %}
          <p>Нет объектов для отображения.</p>
        {% endfor %}
      </div>
    </div>  
  </div>