tasker/engineers/urls.py
from django.urls import path


from . import views

app_name = 'engineers'

urlpatterns = [
    path('', views.index,
         name='index'),
    path('service_zones/', views.service_zones, name='service_zones'),
    path('create_service_zone/', views.create_service_zone,
         name='create_service_zone'),
    path('service_zone/<int:service_zone_id>/delete/',
         views.service_zone_delete, name='service_zone_delete'),
    path('service_zone/<int:service_zone_id>/edit/',
         views.service_zone_edit, name='service_zone_edit'),
     path('service_zone/<int:service_zone_id>/deteil/',
         views.service_zone_deteil, name='service_zone_deteil'),
    path('technicians/', views.technicians, name='technicians'),
    path('technician/<int:technician_id>/detail/',
         views.technician_detail, name='technician_detail'),
    path('technician/<int:technician_id>/activate/',
         views.technician_activate, name='technician_activate'),
    path('technician/<int:technician_id>/deactivate/',
         views.technician_deactivate, name='technician_deactivate'),
    path('technician_zone/<int:technician_zone_id>/delete/',
         views.technician_zone_delete, name='technician_zone_delete'),
    path('fire_alarm_objects/', views.fire_alarm_objects,
         name='fire_alarm_objects'),
    path('fire_alarm_objects/<int:to_date>/', views.fire_alarm_objects_filter,
         name='fire_alarm_objects_filter'),
    path('fire_alarm_object/create/', views.create_fire_alarm_object,
         name='create_fire_alarm_object'),
    path('fire_alarm_object/<int:object_id>/edite/',
         views.fire_alarm_object_edite, name='fire_alarm_object_edite'),
    path('fire_alarm_object/<int:object_id>/delete/',
         views.fire_alarm_object_delete, name='fire_alarm_object_delete'),
    path('fire_alarm_object/<int:object_id>/detail/', views.fire_alarm_object_detail, name = 'fire_alarm_object_detail'),
    path('import_csv/', views.import_csv, name ='import_csv')
]

tasker/tasker/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from users import views
from django.urls import reverse_lazy
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('engineers/', include('engineers.urls', namespace='engineers')),
    path('technicians/', include('technicians.urls', namespace='technicians.urls')),

    #################### Регистрация, и смена пароля##########################
    path('login', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('signup/', views.SignUp.as_view(template_name='users/signup.html'),
         name='signup'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        success_url=reverse_lazy('password_reset_done')
    ), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('password_reset_complete')
    ), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change_form.html'),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),
    ##########################################################

    path('', include('users.urls', namespace='users')),

]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

tasker/users/urls.py
from django.urls import path


from . import views

app_name = 'users'

urlpatterns = [
    path('account_not_confirmed/', views.account_not_confirmed,
         name='account_not_confirmed'),
    path('', views.division_users,
         name='index'),
]

tasker/fire_alarm_objects/models.py
from django.db import models
import os
from django.core.files import File
from service_zones.models import ServiceZone
from branches.models import Branch
from django.utils import timezone
from dateutil.relativedelta import relativedelta
from service_оrganizations.models import ServiceOrganizations
from shapely.geometry import Polygon, Point
from technicians.models import Technician
from tasker.settings import MEDIA_ROOT


class Address(models.Model):
    """
    Модель адреса объекта
    """
    address = models.CharField(max_length=200, verbose_name="Адрес")
    latitude = models.FloatField(verbose_name="Широта", null=True, blank=True)
    longitude = models.FloatField(
        verbose_name="Долгота", null=True, blank=True)

    class Meta:
        verbose_name = 'Адрес'
        verbose_name_plural = 'Адреса'

    def __str__(self):
        return self.address

    def get_geopoint(self):
        return f'[{self.latitude},{self.longitude}]'
    
    def get_geopoint_v2(self):
        return f'{self.latitude},{self.longitude}'
    
    def get_navigator_link(self):
        return f'yandexnavi://build_route_on_map?lat_to={self.latitude}&lon_to={self.longitude}'


class FireAlarmObject(models.Model):
    FREQUENCY_CHOICES = (
        ('Ежемесячно', 'Ежемесячно'),
        ('Ежеквартально', 'Ежеквартально'),
    )

    name = models.CharField(
        max_length=500,
        verbose_name='название объекта',
        help_text='Название объекта, на котором установлена пожарная сигнализация.'
    )

    frequency = models.CharField(
        max_length=15,
        choices=FREQUENCY_CHOICES,
        verbose_name='периодичность обслуживания',
        help_text='Периодичность обслуживания пожарной сигнализации на объекте.'
    )

    last_service_date = models.DateField(
        verbose_name='дата последнего обслуживания',
        help_text='Дата последнего обслуживания пожарной сигнализации на объекте.'
    )

    next_service_date = models.DateField(
        verbose_name='дата следующего обслуживания',
        help_text='Дата следующего обслуживания пожарной сигнализации на объекте.',
        blank=True,
        null=True
    )

    photo = models.ImageField(
        verbose_name='фото объекта',
        help_text='Фотография объекта, на котором установлена пожарная сигнализация.',
        blank=True,
        null=True,
        upload_to='service_photos/'
    )

    address = models.ForeignKey(
        Address,
        on_delete=models.CASCADE,
        verbose_name='Адрес объекта',
        related_name='fire_alarm_objects')

    branch = models.ForeignKey(
        Branch,
        on_delete=models.CASCADE,
        verbose_name='филиал',
        help_text='Филиал, к которому относится данный объект.',
        related_name='fire_alarm_objects'
    )

    service_zone = models.ForeignKey(
        ServiceZone,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="Зона обслуживания",
        related_name="fire_alarm_objects")

    service_organizations = models.ForeignKey(
        ServiceOrganizations,
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
        verbose_name="Обслуживающия организация",
        related_name="fire_alarm_objects"
    )

    remote_number = models.CharField(verbose_name='Пультовый номер',
                                     max_length=20,
                                      blank=True,
                                      null=True)

    room_number = models.CharField(verbose_name='Помещение',
                                   max_length=50,
                                   blank=True,
                                   null=True)
    contract_number = models.CharField(verbose_name='Номер договора',
                                       max_length=50,
                                       blank=True,
                                       null=True)
    contract_date = models.DateField(
        verbose_name='Дата заключения договора',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'объект'
        verbose_name_plural = 'объекты'

    def save(self, *args, **kwargs):
        if not self.photo:
            default_image_path = os.path.join(MEDIA_ROOT, 'default_image.jpg')
            with open(default_image_path, 'rb') as f:
                default_image = File(f)
                self.photo.save('default_image.jpg', default_image, save=False)
        if not self.last_service_date:
            self.last_service_date = timezone.now().date()
        if not self.next_service_date:
            if self.frequency == 'Ежемесячно':
                self.next_service_date = self.last_service_date + \
                    relativedelta(months=1)
            elif self.frequency == 'Ежеквартально':
                self.next_service_date = self.last_service_date + \
                    relativedelta(months=3)
        super().save(*args, **kwargs)

    def update_next_service_date(self):
        if self.frequency == 'Ежемесячно':
            self.next_service_date = self.last_service_date + \
                relativedelta(months=1)
        elif self.frequency == 'Ежеквартально':
            self.next_service_date = self.last_service_date + \
                relativedelta(months=3)
        self.save()

    def __str__(self):
        return self.name

    def auto_add_service_zone(self):
        geopoint = Point(eval(self.address.get_geopoint()))
        zones = ServiceZone.objects.filter(branch=self.branch)
        for zone in zones:
            if Polygon(eval(zone.geopoints)).contains(geopoint):
                self.service_zone = zone
                self.save()
                return True
        return False


class FireAlarmObjectService(models.Model):
    """
    Модель технического обслуживания пожарной сигнализации
    """
    fire_alarm_object = models.ForeignKey(
        FireAlarmObject, on_delete=models.CASCADE, verbose_name='Объект', related_name='service_done')
    service_date = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата создания')
    technician = models.ForeignKey(
        Technician, blank=True,
        null=True, on_delete=models.PROTECT, verbose_name='Техник', related_name='service_done')
    service_journal_title_page_photo = models.ImageField(
        upload_to='service_photos/', 
        verbose_name='Фотография обложки журнала техобслуживания ПС',
        blank=True, 
        default='media/default_image.jpg'
    )
    service_journal_photo = models.ImageField(
        upload_to='service_photos/', verbose_name='Фотография журнала техобслуживания ПС')
    control_panel_photo = models.ImageField(
        upload_to='service_photos/', verbose_name='Фотография головного прибора ПС')
    comment = models.TextField(blank=True, verbose_name='Комментарий')

    class Meta:
        verbose_name = 'Обслуживание объекта'
        verbose_name_plural = 'Обслуживания объектов'

    def save(self, *args, **kwargs):
        # при сохранении устанавливаем last_service_date на текущую дату у связанного объекта
        self.fire_alarm_object.last_service_date = timezone.now()
        self.fire_alarm_object.update_next_service_date()
        pending_failed_services = FailedService.objects.filter(
            fire_alarm_object=self.fire_alarm_object, status__in=['pending', 'in_progress'])
        for failed_service in pending_failed_services:
            failed_service.status = 'completed'
            failed_service.save()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Обслуживание {self.fire_alarm_object} от {self.service_date}'


class FailedService(models.Model):
    """
    Модель неудавшегося обслуживания пожарной сигнализации
    """
    status_choices = [
        ('pending', 'В ожидании'),
        ('in_progress', 'Выполняется'),
        ('completed', 'Завершено'),
    ]
    technician = models.ForeignKey(
        Technician, on_delete=models.PROTECT, verbose_name='Техник', related_name='failed_services')
    status = models.CharField(choices=status_choices,
                              max_length=255, default='pending')
    service_date = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата создания')
    fire_alarm_object = models.ForeignKey(
        FireAlarmObject, on_delete=models.CASCADE, related_name='failed_services')
    photo = models.ImageField(
        upload_to='failed_service_photos/', verbose_name='Фото неисправности', blank=True,
        null=True,)

    comment = models.TextField(verbose_name='Комментарий')
    
    class Meta:
        verbose_name = 'Проблема с обслуживания'
        verbose_name_plural = 'Проблемы с обслуживаниями'
        
    def __str__(self):
        return f"{self.fire_alarm_object} - {self.service_date }"

tasker/fire_alarm_objects/forms.py
from django import forms
from .models import FireAlarmObject, FireAlarmObjectService, FailedService
from dadata import Dadata
from .models import Address
from tasker.settings import DADATA_SECRET, DADATA_TOKEN
from service_zones.models import ServiceZone

class FireAlarmObjectForm(forms.ModelForm):
    address = forms.CharField(required=True,
                              max_length=200,
                              label='Адресс',
                              help_text='Введите адресс',)
    latitude = forms.CharField(required=False,
                               max_length=200,
                               label='Широта',
                               help_text='Введите широту',)
    longitude = forms.CharField(required=False,
                                max_length=200,
                                label='Долгота',
                                help_text='Введите долготу',)

    class Meta:
        model = FireAlarmObject
        fields = ('name',
                  'latitude',
                  'longitude',
                  'address',
                  'room_number',
                  'service_organizations',
                  'frequency',
                  'remote_number',
                  'contract_number',
                  'contract_date',
                  'last_service_date',
                  'photo')

    def __init__(self, engineer=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance:
            self.initial['address'] = self.instance.address.address
        self.fields['last_service_date'].widget.attrs['placeholder'] = (
            'дд.мм.гггг')
        self.fields['contract_date'].widget.attrs['placeholder'] = (
            'дд.мм.гггг')

    def clean_address(self):
        address = self.cleaned_data.get('address')
        dadata = Dadata(token=DADATA_TOKEN, secret=DADATA_SECRET)
        result = dadata.clean("address", address)
        verification_status = result['qc']
        if verification_status != 0:
            if self.cleaned_data.get('latitude') and self.cleaned_data.get('longitude'):
                address_object, status = Address.objects.get_or_create(
                    address=address,
                    latitude=self.cleaned_data.get('latitude'),
                    longitude=self.cleaned_data.get('longitude'))
                return address_object
            raise forms.ValidationError(
                'Адрес не распознан. Добавте координады для добавления объекта.')
        address = result['result']
        latitude = result['geo_lat']
        longitude = result['geo_lon']
        address_object, status = Address.objects.get_or_create(
            address=address,
            latitude=latitude,
            longitude=longitude)
        return address_object


class FireAlarmObjectServiceForm(forms.ModelForm):
    class Meta:
        model = FireAlarmObjectService
        fields = ('service_journal_title_page_photo','service_journal_photo', 'control_panel_photo', 'comment')


class FailedServiceForm(forms.ModelForm):
    class Meta:
        model = FailedService
        fields = ('photo', 'comment')

tasker/fire_alarm_objects/views.py
from django.shortcuts import render

# Create your views here.

tasker/templates/engineers/fire_alarm_object/includes/fire_alarm_object_failed_service.html
{% load thumbnail %}
<div class="accordion" id="accordion-fire_alarm_object_failed_service{{fire_alarm_object_failed_service.id}}">
    <div class="card mb-1 mt-1" >
      <div class="card-body"  data-bs-toggle="collapse" data-bs-target="#collapse-fire_alarm_object_failed_service{{fire_alarm_object_failed_service.id}}">
        <div class ='row'>  
              <div class = 'col-6'>
                <h5>{{fire_alarm_object_failed_service}}</h5><p>
              </div>
              <div class = 'col-6'>
                {% if fire_alarm_object.photo %}
                {% thumbnail fire_alarm_object.photo "70x70" crop="center" as im %}
                  <a href="{{ fire_alarm_object.photo.url }}"><img class="img-thumbnail float-end" src="{{ im.url }}"></a>
                {% endthumbnail %}
                {% endif %} 
              </div>
        </div>
      </div>
      <div id="collapse-fire_alarm_object_failed_service{{fire_alarm_object_failed_service.id}}" class="accordion-collapse collapse" aria-labelledby="heading-fire_alarm_object_failed_service{{fire_alarm_object_failed_service.id}}" data-bs-parent="#accordion-fire_alarm_object_failed_service{{fire_alarm_object_failed_service.id}}">
        <div class="card-body">

        </div>
      </div>
    </div>
</div>

tasker/templates/engineers/fire_alarm_object/includes/fire_alarm_object_filter.html
<div class ="card mt-1 mb-1">
  <div class="card-body">
    <a href="{% url 'engineers:fire_alarm_objects'%}" class="btn btn-secondary btn-sm p-1 m-1">все</a>
    <a href="{% url 'engineers:fire_alarm_objects_filter' days_left_in_month%}" class="btn btn-secondary btn-sm p-1 m-1">до конца месяца</a>
    <a href="{% url 'engineers:fire_alarm_objects_filter' 3 %}" class="btn btn-danger btn-sm p-1 m-1">менее 3 дней</a>
    <a href="{% url 'engineers:fire_alarm_objects_filter' 6 %}" class="btn btn-warning btn-sm p-1 m-1">менее 6 дней</a>
    <a href="{% url 'engineers:fire_alarm_objects_filter' 9 %}" class="btn btn-primary btn-sm p-1 m-1">менее 9 дней</a>
  </div>
</div>

tasker/templates/engineers/fire_alarm_object/includes/fire_alarm_object_info.html
{% load thumbnail %}
<div class="accordion" id="accordion-fire_alarm_object{{fire_alarm_object.id}}-info">
    <div class="card mb-1 mt-1" >
      <div class="card-body"  data-bs-toggle="collapse" data-bs-target="#collapse-fire_alarm_object{{fire_alarm_object.id}}-info"  aria-controls="collapse-fire_alarm_object{{fire_alarm_object.id}}-info">
        <div class ='row'>  
              <div class = 'col-6'>
                <h5>{{fire_alarm_object}}</h5><p>
                Адресс: {{fire_alarm_object.address}}
              </div>
              <div class = 'col-6'>
                {% if fire_alarm_object.photo %}
                {% thumbnail fire_alarm_object.photo "70x70" crop="center" as im %}
                  <a href="{{ fire_alarm_object.photo.url }}"><img class="img-thumbnail float-end" src="{{ im.url }}"></a>
                {% endthumbnail %}
                {% endif %} 
              </div>
        </div>
      </div>
      <div id="collapse-fire_alarm_object{{fire_alarm_object.id}}-info" class="accordion-collapse collapse" aria-labelledby="heading-fire_alarm_object{{fire_alarm_object.id}}-info" data-bs-parent="#accordion-fire_alarm_object{{fire_alarm_object.id}}-info">
        <div class="card-body">
          <p class="card-text">Обслуживающая организация: {{ fire_alarm_object.service_organizations }}</p>
          <p class="card-text">Переодичность: {{ fire_alarm_object.frequency }}</p>
          <p class="card-text">Зона обслуживания: {{ fire_alarm_object.service_zone }}</p>
          <p class="card-text">Последняя дата обслуживания: {{ fire_alarm_object.last_service_date }}</p>
          <p class="card-text">Следующая дата обслуживания: {{ fire_alarm_object.next_service_date }}</p>
          <div class="d-grid gap-2 gap-2 d-md-block">   
            {% if show_delete %}
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                Удалить объект
              </button>
              <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h1 class="modal-title fs-5" id="staticBackdropLabel">Вы уверены что хотите удалить {{ fire_alarm_object.name }}</h1>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                      <a href="{% url 'engineers:fire_alarm_object_delete' fire_alarm_object.id%}" type ="bottom" class="btn btn-primary">Удалить</a>
                    </div>
                  </div>
                </div>
              </div>
            {% else %}
              <a href="{% url 'engineers:fire_alarm_object_detail' fire_alarm_object.id %}">
                <button class="btn btn-primary">
                  Подробнее
                </button>
              </a>
            {% endif %}
            {% if assign_zone_to_object_form%}
                <a class="btn btn-primary " data-bs-toggle="collapse" href="#collapse-add_zone2fire_alarm_object_form" role="button" aria-expanded="false" aria-controls="collapse-add_zone2fire_alarm_object_form">
                    Изменить зону
                </a>
            {% endif %}
            {% if is_edite %}
            <a href="{% url 'engineers:fire_alarm_object_edite' fire_alarm_object.id %}">
              <button class="btn btn-primary">
                Редактировать
              </button>
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
</div>
<div class="collapse mb-2" id="collapse-add_zone2fire_alarm_object_form">
  <div class="card card-body">
    <form id="add_zone2fire_alarm_object_form" method="POST" enctype="multipart/form-data" action="{% url 'engineers:fire_alarm_object_detail' fire_alarm_object.id %}">
      {% csrf_token %}
      {{ assign_zone_to_object_form.as_p }}
      <button id="add_zone2fire_alarm_object_form" class="btn btn-success btn-sm">Сохранить зону</button>
    </form>
  </div>
</div>

tasker/templates/engineers/fire_alarm_object/includes/fire_alarm_object_service.html
{% load thumbnail %}
<div class="accordion" id="accordion-fire_alarm_object_service{{fire_alarm_object_service.id}}">
    <div class="card mb-1 mt-1" >
      <div class="card-body"  data-bs-toggle="collapse" data-bs-target="#collapse-fire_alarm_object_service{{fire_alarm_object_service.id}}"  aria-controls="collapse-fire_alarm_object_service{{fire_alarm_object_service.id}}">
        <div class ='row'>  
              <div class = 'col-6'>
                <h5>{{fire_alarm_object_service}}</h5><p>
              </div>
              <div class = 'col-6'>
                {% if fire_alarm_object.photo %}
                {% thumbnail fire_alarm_object.photo "70x70" crop="center" as im %}
                  <a href="{{ fire_alarm_object.photo.url }}"><img class="img-thumbnail float-end" src="{{ im.url }}"></a>
                {% endthumbnail %}
                {% endif %} 
              </div>
        </div>
      </div>
      <div id="collapse-fire_alarm_object_service{{fire_alarm_object_service.id}}" class="accordion-collapse collapse" aria-labelledby="heading-fire_alarm_object_service{{fire_alarm_object_service.id}}" data-bs-parent="#accordion-fire_alarm_object_service{{fire_alarm_object_service.id}}">
        <div class="card-body">

        </div>
      </div>
    </div>
</div>